export const LOGIN_ACTIONS = {
  LOGIN_REQUEST: 'LOGIN.REQUEST',
  SET_TOKEN: 'SET.TOKEN',
  LOGIN_SUCCESS: 'LOGIN.SUCCESS',
  LOGIN_FAILURE: 'LOGIN.FAILURE',
  LOGOUT: 'LOGOUT',
  INVALID_TOKEN: 'INVALID.TOKEN',
  REQUEST_LOGOUT: 'REQUEST.LOGOUT',
  DELETE_ERROR: 'DELETE.ERROR',
};

export const APP_ACTIONS = {
  APP_BUSY_PUSH: 'APP_BUSY.PUSH',
  APP_BUSY_POP: 'APP_BUSY.POP',
};

export const USER_ACTIONS = {
  GET_USER_SUCCESS: 'GET_USER.SUCCESS',
  GET_USER_FAILURE: 'GET_USER.FAILURE',
  GET_ALL_USERS_SUCCESS: 'GET.ALL.USERS.SUCCESS',
  GET_ALL_USERS_FAILURE: 'GET.ALL.USERS.FAILURE',
  EDIT_USER_SUCCESS: 'EDIT_USER.SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER.FAILURE',
};

export const REGISTER_ACTIONS = {
  REGISTER_SUCCESS: 'REGISTER.SUCCESS',
  REGISTER_FAILURE: 'REGISTER.FAILURE',
  REGUSTER_DELETE_ERROR: 'REGUSTER_DELETE.ERROR'

};


export const SERVICE_ACTIONS = {
  GET_SERVICES_SUCCESS: 'GET_SERVICES.SUCCESS',
  GET_SERVICES_FAILURE: 'GET_SERVICES.FAILURE',
  SET_SELECTED_SERVICE: 'SET_SELECTED.SERVICE',
  ADD_SERVICE_SUCCESS: 'ADD_SERVICE.SUCCESS',
  ADD_SERVICE_FAILURE: 'ADD_SERVICE.FAILURE',
  EDIT_SERVICE_SUCCESS: 'EDIT_SERVICE.SUCCESS',
  EDIT_SERVICE_FAILURE: 'EDIT_SERVICE.FAILURE',
  DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE.SUCCESS',
  DELETE_SERVICE_FAILURE: 'DELETE_SERVICE.FAILURE',

  ADD_CUSTOM_RESERVATION_LIMIT_SUCCESS: 'ADD_CUSTOM_RESERVATION_LIMIT.SUCCESS',
  ADD_CUSTOM_RESERVATION_LIMIT_FAILURE: 'ADD_CUSTOM_RESERVATION_LIMIT.FAILURE',
  ADD_WEEK_CUSTOM_RESERVATION_LIMIT_SUCCESS: 'ADD_WEEK_CUSTOM_RESERVATION_LIMIT.SUCCESS',
  ADD_WEEK_CUSTOM_RESERVATION_LIMIT_FAILURE: 'ADD_WEEK_CUSTOM_RESERVATION_LIMIT.FAILURE',

  GET_RESERVATION_LIMIT_BY_DATE_SUCCES: 'GET_RESERVATION_LIMIT_BY_DATE.SUCCESS',
  GET_RESERVATION_LIMIT_BY_DATE_FAILURE: 'GET_RESERVATION_LIMIT_BY_DATE.FAILURE', 
  GET_RESERVATION_LIMITS_SUCCES: 'GET_RESERVATION_LIMITS.SUCCESS',
  GET_RESERVATION_LIMITS_FAILURE: 'GET_RESERVATION_LIMITS.FAILURE'

};

export const CAR_ACTIONS = {
  GET_CARS_SUCCESS: 'GET_CARS.SUCCESS',
  GET_CARS_FAILURE: 'GET_CARS.FAILURE',
  ADD_CAR_SUCCESS: 'ADD_CAR.SUCCESS',
  ADD_CAR_FAILURE: 'ADD_CAR.FAILURE',
  EDIT_CAR_SUCCESS: 'EDIT_CAR.SUCCESS',
  EDIT_CAR_FAILURE: 'EDIT_CAR.FAILURE',
  DELETE_CAR_SUCCESS: 'DELETE_CAR.SUCCESS',
  DELETE_CAR_FAILURE: 'DELETE_CAR.FAILURE',

  GET_CAR_PROBLEMS_SUCCESS: 'GET_CAR_PROBLEMS.SUCCESS',
  GET_CAR_PROBLEMS_FAILURE: 'GET_CAR_PROBLEMS.FAILURE',
};

export const CAR_REPAIR_ACTIONS = {
  GET_CARS_REPAIR_SUCCESS: 'GET_CARS_REPAIR.SUCCESS',
  GET_CARS_REPAIR_FAILURE: 'GET_CARS_REPAIR.FAILURE',
  ADD_CAR_REPAIR_SUCCESS: 'ADD_CAR_REPAIR.SUCCESS',
  ADD_CAR_REPAIR_FAILURE: 'ADD_CAR_REPAIR.FAILURE',
  EDIT_CAR_REPAIR_SUCCESS: 'EDIT_CAR_REPAIR.SUCCESS',
  EDIT_CAR_REPAIR_FAILURE: 'EDIT_CAR_REPAIR.FAILURE',
  DELETE_CAR_REPAIR_SUCCESS: 'DELETE_CAR_REPAIR.SUCCESS',
  DELETE_CAR_REPAIR_FAILURE: 'DELETE_CAR_REPAIR.FAILURE'
};

export const RESERVATION_ACTIONS = {
  GET_RESERVATION_SUCCESS: 'GET_RESERVATION.SUCCESS',
  GET_RESERVATION_FAILURE: 'GET_RESERVATION.FAILURE',
  ADD_RESERVATION_SUCCESS: 'ADD_RESERVATION.SUCCESS',
  ADD_RESERVATION_FAILURE: 'ADD_RESERVATION.FAILURE',
  EDIT_RESERVATION_SUCCESS: 'EDIT_RESERVATION.SUCCESS',
  EDIT_RESERVATION_FAILURE: 'EDIT_RESERVATION.FAILURE',
  DELETE_RESERVATION_SUCCESS: 'DELETE_RESERVATION.SUCCESS',
  DELETE_RESERVATION_FAILURE: 'DELETE_RESERVATION.FAILURE',
  EDIT_RESERVATION_LIMIT_SUCCESS: 'EDIT_RESERVATION_LIMIT.SUCCESS',
  EDIT_RESERVATION_LIMIT_FAILURE: 'EDIT_RESERVATION_LIMIT.FAILURE',
};

export const MESSAGE_ACTIONS = {
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES.SUCCESS',
  GET_MESSAGES_FAILURE: 'GET_MESSAGES.FAILURE',
  ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE.SUCCESS',
  ADD_MESSAGE_FAILURE: 'ADD_MESSAGE.FAILURE',

  SEEN_MESSAGE_SUCCESS: 'SEEN_MESSAGE.SUCCESS',
  SEEN_MESSAGE_FAILURE: 'SEEN_MESSAGE.FAILURE',

  ADD_CHAT_PARTNER_SUCCESS: 'ADD.CHAT.PARTNER.SUCCESS',

};