stages:
  - build
  - test
  - checkstyle
  - deploy

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - mvn clean package

test:
    stage: test
    image: maven:3.3.9-jdk-8
    script:
    - echo "Test DEMO app"
    - mvn test && mvn jacoco:report
    coverage: "/Total.*?([0-9]{1,3})%/"


checkstyle:
    stage: checkstyle
    image: maven:3.3.9-jdk-8
    script:
    - echo "Checkstyle DEMO app"
    - mvn checkstyle:check

variables:
    DB_IP: ec2-34-250-19-18.eu-west-1.compute.amazonaws.com
    DB_PORT: 5432
    DB_USER: oqcivtxzjzrxxc
    DB_PASSWORD: be39f7a9f29bb4f4fcec95141199270c64b15d5b7477ca898cf9ea6ef9bdfb39
    DB_DBNAME: ddaqn0l8crbb1g
    
deploy:
  stage: deploy
  image: ruby:2.4
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=spring-demo-ds-roman-alexandru --api-key=$HEROKU_API_KEY
  only:
    - production
